### ISSUE TITLE
western stations

### ISSUE THREAD

**Issue by ciiram** [kaburia/bson#5]
Can you try and derive this list of Western Kenya stations automatically 

western_stations = ['TA00001',
                    'TA00019',
                    'TA00018',
                    'TA00076',
                    'TA00077',
                    'TA00061',
                    'TA00031',
                    'TA00442',
                    'TA00440',
                    'TA00389',
                    'TA00441',
                    'TA00469',
                    'TA00388',
                    'TA00394',
                    'TA00587',
                    'TA00387']

**Comment by kaburia** [comment]
Issue fixed by drawing a radius around the given address and capturing the stations nearby
To get the list of stations within that radius  the function filterStationsList(address, distance) is available
![image](https://user-images.githubusercontent.com/88529649/221857485-7add18ec-e90b-4937-9e03-af93dd68f74f.png)
 

To get the stations data the function filterStations(address, distance, startDate, endDate) 
![image](https://user-images.githubusercontent.com/88529649/221856949-b16befb4-7cea-4857-a2b4-e27250f34f2e.png)
